apiVersion: {{ .Values.service.imageVersion }}
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-port
    protocol: TCP
    port: {{ .Values.service.port }} # service port
    targetPort: {{ .Values.service.port }} # container port